project:
  status: active
  name: omero/gatsby-casper
  buildStatus: ready
  external: false
  provider: github
  deployment:
    buildCommand: gatsby build
    builds:
      master:
        weight: 1
        id: _dcqnjp279
        environmentVariables: []
        branch: master
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
    contentDirectory:
      - src/content
  type: gatsby
schemas:
  - type: dataset
    definitions:
      schema:
        name: Tag
        id: tag
      fields:
        - name: Id
          type: string
          required: true
          value: ''
          id: id
          orderable: true
          removable: true
          system: false
          widget: text
        - system: false
          widget: textarea
          name: Description
          type: string
          required: true
          value: ''
          id: description
          orderable: true
          removable: true
        - widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
          removable: true
          system: false
    schema:
      json:
        required:
          - id
          - description
          - image
        type: object
        properties:
          description:
            title: Description
            default: ''
            type: string
          id:
            title: Id
            default: ''
            type: string
          image:
            title: Image
            default: ''
            type: string
      name: Tag
      ui:
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - id
          - description
          - image
          - '*'
        description:
          'ui:widget': textarea
        id:
          'ui:widget': text
  - type: form
    definitions:
      fields:
        - id: name
          widget: text
          name: Name
          required: false
          type: string
        - id: message
          widget: textarea
          name: Message
          required: false
          type: string
      schema:
        id: contact
        name: Contact
    schema:
      ui:
        message:
          'ui:widget': textarea
        name:
          'ui:widget': text
        'ui:order':
          - name
          - message
          - '*'
      json:
        required: []
        type: object
        properties:
          name:
            default: ''
            type: string
            title: Name
          message:
            default: ''
            type: string
            title: Message
      name: Contact
  - type: content
    definitions:
      schema:
        name: Page
        id: page
      fields:
        - type: string
          required: true
          value: ''
          id: title
          orderable: true
          removable: true
          system: false
          widget: text
          name: Title
        - removable: true
          system: false
          widget: textarea
          name: Excerpt
          type: string
          required: true
          value: ''
          id: excerpt
          orderable: true
        - value: ''
          id: content
          orderable: true
          removable: true
          system: false
          widget: SlateEditor
          name: Content
          type: string
          required: true
        - type: string
          required: true
          value: ''
          id: image
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Image
        - orderable: true
          removable: true
          system: false
          widget: DatePicker
          name: Date
          type: string
          required: true
          value: ''
          id: date
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Author
          type: string
          required: true
          value: ''
          id: author
        - widget: text
          name: Draft
          type: string
          required: true
          value: ''
          id: draft
          orderable: true
          removable: true
          system: false
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Tags
          type: string
          required: true
          value: ''
          id: tags
    schema:
      json:
        properties:
          author:
            default: ''
            type: string
            title: Author
          excerpt:
            default: ''
            type: string
            title: Excerpt
          image:
            default: ''
            type: string
            title: Image
          content:
            title: Content
            default: ''
            type: string
          date:
            default: ''
            type: string
            title: Date
          tags:
            default: ''
            type: string
            title: Tags
          draft:
            title: Draft
            default: ''
            type: string
          title:
            default: ''
            type: string
            title: Title
        required:
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
        type: object
      name: Page
      ui:
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        tags:
          'ui:widget': text
        draft:
          'ui:widget': text
        title:
          'ui:widget': text
        author:
          'ui:widget': text
        excerpt:
          'ui:widget': textarea
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
          - '*'
  - type: dataset
    definitions:
      schema:
        id: author
        name: Author
      fields:
        - system: false
          widget: text
          name: Id
          type: string
          required: true
          value: ''
          id: id
          orderable: true
          removable: true
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Avatar
          type: string
          required: true
          value: ''
          id: avatar
        - orderable: true
          removable: true
          system: false
          widget: textarea
          name: Bio
          type: string
          required: true
          value: ''
          id: bio
        - removable: true
          system: false
          widget: text
          name: Facebook
          type: string
          required: true
          value: ''
          id: facebook
          orderable: true
        - name: Location
          type: string
          required: true
          value: ''
          id: location
          orderable: true
          removable: true
          system: false
          widget: text
        - removable: true
          system: false
          widget: MediaSchema
          name: Profile_image
          type: string
          required: true
          value: ''
          id: profile_image
          orderable: true
        - system: false
          widget: text
          name: Twiter
          type: string
          required: true
          value: ''
          id: twiter
          orderable: true
          removable: true
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Twitter
          type: string
          required: true
          value: ''
          id: twitter
        - type: string
          required: true
          value: ''
          id: website
          orderable: true
          removable: true
          system: false
          widget: text
          name: Website
    schema:
      ui:
        twitter:
          'ui:widget': text
        facebook:
          'ui:widget': text
        bio:
          'ui:widget': textarea
        'ui:order':
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
          - '*'
        profile_image:
          'ui:widget': MediaSchema
        avatar:
          'ui:widget': MediaSchema
        id:
          'ui:widget': text
        location:
          'ui:widget': text
        twiter:
          'ui:widget': text
        website:
          'ui:widget': text
      json:
        properties:
          bio:
            default: ''
            type: string
            title: Bio
          profile_image:
            title: Profile_image
            default: ''
            type: string
          avatar:
            title: Avatar
            default: ''
            type: string
          id:
            default: ''
            type: string
            title: Id
          location:
            default: ''
            type: string
            title: Location
          twiter:
            title: Twiter
            default: ''
            type: string
          website:
            default: ''
            type: string
            title: Website
          twitter:
            default: ''
            type: string
            title: Twitter
          facebook:
            default: ''
            type: string
            title: Facebook
        required:
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
        type: object
      name: Author
mapping:
  content:
    - schema: page
      path: src/content/welcome.md
    - schema: page
      path: src/content/using-gatsby.md
    - schema: page
      path: src/content/a-full-style-test.md
    - schema: page
      path: src/content/google-spreadsheet-manage-content.md
    - schema: page
      path: src/content/how-run-puppeteer-headless-chrome.md
    - schema: page
      path: src/content/gatsby-wax.md
    - schema: page
      path: src/content/great-catsby.md
  dataset:
    - schema: author
      path: src/content/author.yaml
    - schema: tag
      path: src/content/tag.yaml
  form: []
